# Generated by Django 5.1.3 on 2025-06-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilepic.svg', upload_to='profile_picture'),
        ),
    ]
