# Generated by Django 5.1.3 on 2025-06-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='nothing', max_length=500),
        ),
    ]
