# Generated by Django 5.1.3 on 2025-06-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://hips.hearstapps.com/hmg-prod/images/detroit-style-pizza-recipe-1-64429e4a2e324.jpg?crop=0.974xw:0.974xh;0.0255xw,0&resize=640:*', max_length=500),
        ),
    ]
